package models.farming;

public enum SeedType {
    APRICOT_SAPLING,
    CHERRY_SAPLING,
    BANANA_SAPLING,
    MANGO_SAPLING,
    ORANGE_SAPLING,
    PEACH_SAPLING,
    APPLE_SAPLING,
    POMEGRANATE_SAPLING,
    ACORNS,
    MAPLE_SEEDS,
    PINE_CONES,
    MAHOGANY_SEEDS,
    MUSHROOM_TREE_SEEDS,
    MYSTIC_TREE_SEEDS
}
