package models.crafting;

import models.tools.BackPackable;

import java.util.HashMap;

public enum CraftItemType {
    CHERRY_BOMB("4 copper ore + 1 coal = 1 cherry bomb",
            new HashMap<>(),
            Ability.miningAbility,
            1,
            50),
    BOMB("4 iron ore + 1 coal = 1 bomb",
            new HashMap<>(),
            Ability.miningAbility,
            2,
            50),
    MEGA_BOMB("4 gold ore + 1 coal = 1 mega bomb",
            new HashMap<>(),
            Ability.miningAbility,
            3,
            50),
    SPRINKLER("1 copper bar + 1 iron bar = 1 sprinkler",
            new HashMap<>(),
            Ability.farmingAbility,
            1,
            0),
   QUALITY_SPRINKLER("1 iron bar + 1 gold bar = 1 quality sprinkler",
                      new HashMap<>(),
    Ability.farmingAbility,
            2,
            0),
    IRIDIUM_SPRINKLER("1 gold bar + 1 iridium bar = 1 iridium sprinkler",
            new HashMap<>(),
            Ability.farmingAbility,
            3,
            0),
    CHARCOAL_KLIN("20 wood + 2 copper bar = 1 charcoal klin",
            new HashMap<>(),
            Ability.foragingAbility,
            1,
            0),
    FURNACE("20 copper ore + 25 stone = 1 furnace",
            new HashMap<>(),
            null,
            0,
            0),
    SCARECROW("50 wood + 1 coal + 20 fiber = 1 scarecrow",
            new HashMap<>(),
            null,
            0,
            0),
    DELUXE_SCARECROW("50 wood + 1 coal + 20 fiber + 1 iridium ore = 1 deluxe scarecrow",
            new HashMap<>(),
            Ability.farmingAbility,
            2,
            0),
    BEE_HOUSE("40 wood + 8 coal + 1 iron bar = 1 bee house",
            new HashMap<>(),
            Ability.farmingAbility,
            1,
            0),
    CHEESE_PRESS("45 wood + 45 stone + 1 copper bar = 1 cheese press",
            new HashMap<>(),
            Ability.farmingAbility,
            2,
            0),
    KEG("30 wood + 1 copper bar + 1 iron bar = 1 keg",
            new HashMap<>(),
            Ability.farmingAbility,
            3,
            0),
    LOOM("60 wood + 30 fiber = 1 loom",
            new HashMap<>(),
            Ability.farmingAbility,
            3,
            0),
    MAYONNAISE_MACHINE("15 wood + 15 stone + 1 copper bar = 1 mayonnaise machine",
            new HashMap<>(),
            null,
            0,
            0),
    OIL_MAKER("100 wood + 1 gold bar + 1 iron bar = 1 oil maker",
            new HashMap<>(),
            Ability.farmingAbility,
            3,
            0),
    PRESERVES_JAR("50 wood + 40 stone + 8 coal = 1 preserves jar",
            new HashMap<>(),
            Ability.farmingAbility,
            2,
            0),
    DEHYDRATOR("30 wood + 20 stone + 30 fiber = 1 dehydrator",
            new HashMap<>(),
            null,
            0,
            0),
    FISH_SMOKER("50 wood + 3 iron bar + 10 coal = 1 fish smoker",
            new HashMap<>(),
            null,
            0,
            0),
    MYSTIC_TREE_SEED("5 acorn + 5 maple seed + 5 pine cone + 5 mahogany seed = 1 fish smoker",
            new HashMap<>(),
            Ability.foragingAbility,
            4,
            100);
    public final String recipe;
    public final HashMap<BackPackable, Integer> ingredients;
    public final Ability ability;
    public final int levelRequired;
    public final int price;

    CraftItemType(String recipe, HashMap<BackPackable, Integer> ingredients, Ability ability, int levelRequired, int price) {
        this.recipe = recipe;
        this.ingredients = ingredients;
        this.ability = ability;
        this.levelRequired = levelRequired;
        this.price = price;
    }

}
