package models.artisanry;
import models.crafting.CraftItemType;
import models.tools.BackPackable;
import java.util.HashMap;

public enum ArtisanItemType {
    BEER(CraftItemType.KEG,
            "Drink in moderation.",
            50,
            24,
            new HashMap<>(),
            200),
    VINEGAR(CraftItemType.KEG,
            "An aged fermented liquid used in many cooking recipes.",
            13,
            10,
            new HashMap<>(),
            100),
    COFFEE(CraftItemType.KEG,
            "It smells delicious. This is sure to give you a boost.",
            75,
            2,
            new HashMap<>(),
            150),
    JUICE(CraftItemType.KEG,
            "A sweet, nutritious beverage.",
            0,
            96,
            new HashMap<>(),
            0),
    MEAD(CraftItemType.KEG,
            "A fermented beverage made from honey.Drink in moderation.",
            100,
            10,
            new HashMap<>(),
            300),
    PALE_ALE(CraftItemType.KEG,
            "Drink in moderation.",
            50,
            72,
            new HashMap<>(),
            300),
    WINE(CraftItemType.KEG,
            "Drink in moderation.",
            0,
            168,
            new HashMap<>(),
            0),
    HONEY(CraftItemType.BEE_HOUSE,
            "It's a sweet syrup produced by bees.",
            75,
            96,
            new HashMap<>(),
            350),
    CHEESE_MILK(CraftItemType.CHEESE_PRESS,
            "It's your basic cheese.",
            100,
            72,
            new HashMap<>(),
            230),
    CHEESE_LARGE_MILK(CraftItemType.CHEESE_PRESS,
            "It's your basic cheese.",
            100,
            72,
            new HashMap<>(),
            345),
    GOAT_CHEESE_MILK(CraftItemType.CHEESE_PRESS,
            "Soft cheese made from goat's milk.",
            100,
            72,
            new HashMap<>(),
            400),
    GOAT_CHEESE_LARGE_MILK(CraftItemType.CHEESE_PRESS,
            "Soft cheese made from goat's milk.",
            100,
            72,
            new HashMap<>(),
            600),
    DRIED_MUSHROOM(CraftItemType.DEHYDRATOR,
            "A package of gourmet mushrooms.",
            50,
            9,
            new HashMap<>(),
            0),
    DRIED_FRUIT(CraftItemType.DEHYDRATOR,
            "Chewy pieces of dried fruit.",
            75,
            0,
            new HashMap<>(),
            0),
    RAISINS(CraftItemType.DEHYDRATOR,
            "It's said to be the Junimos' favorite food.",
            125,
            0,
            new HashMap<>(),
            600),
    COAL(CraftItemType.CHARCOAL_KLIN,
            "Turns 10 pieces of wood into one piece of coal.",
            0,
            1,
            new HashMap<>(),
            50),
    CLOTH(CraftItemType.LOOM,
            "A bolt of fine wool cloth.",
            0,
            4,
            new HashMap<>(),
            470),
    MAYONNAISE_EGG(CraftItemType.MAYONNAISE_MACHINE,
            "It looks spreadable.",
            50,
            3,
            new HashMap<>(),
            190),
    MAYONNAISE_LARGE_EGG(CraftItemType.MAYONNAISE_MACHINE,
            "It looks spreadable.",
            50,
            3,
            new HashMap<>(),
            237),
    DUCK_MAYONNAISE(CraftItemType.MAYONNAISE_MACHINE,
            "It's a rich, yellow mayonnaise.",
            75,
            3,
            new HashMap<>(),
            37),
    DINOSAUR_MAYONNAISE(CraftItemType.MAYONNAISE_MACHINE,
            "It's thick and creamy, with a vivid green hue.It smells like grass and leather.",
            125,
            3,
            new HashMap<>(),
            800),
    TRUFFLE_OIL(CraftItemType.OIL_MAKER,
            "A gourmet cooking ingredient.",
            38,
            6,
            new HashMap<>(),
            1065),
    OIL_CORN(CraftItemType.OIL_MAKER,
            "All purpose cooking oil.",
            13,
            6,
            new HashMap<>(),
            100),
    OIL_SUNFLOWER(CraftItemType.OIL_MAKER,
            "All purpose cooking oil.",
            13,
            1,
            new HashMap<>(),
            100),
    OIL_SUNFLOWER_SEED(CraftItemType.OIL_MAKER,
            "All purpose cooking oil.",
            13,
            24,
            new HashMap<>(),
            100),
    PICKLES(CraftItemType.PRESERVES_JAR,
            "A jar of your home-made pickles.",
            0,
            6,
            new HashMap<>(),
            0),
    JELLY(CraftItemType.PRESERVES_JAR,
            "Gooey.",
            0,
            72,
            new HashMap<>(),
            0),
    SMOKED_FISH(CraftItemType.FISH_SMOKER,
            "A whole fish, smoked to perfection.",
            0,
            1,
            new HashMap<>(),
            0),
    METAL_BAR(CraftItemType.FURNACE,
            "Turns ore and coal into metal bars.",
            0,
            4,
            new HashMap<>(),
            0);
    public final String description;
    public final int energy;
    public final int productionTimeInHours;
    public final HashMap<BackPackable, Integer> ingredients;
    public final int sellPrice;

    ArtisanItemType(CraftItemType craftItemType,
                    String description,
                    int energy,
                    int productionTimeInHours,
                    HashMap<BackPackable, Integer> ingridients,
                    int sellPrice) {
        this.description = description;
        this.energy = energy;
        this.productionTimeInHours = productionTimeInHours;
        this.ingredients = ingridients;
        this.sellPrice = sellPrice;
    }
}
