package models.cooking;

import models.tools.BackPackable;

import java.util.HashMap;

public enum FoodType {
    FRIED_EGG("1 egg = 1 fried egg",
            new HashMap<>(),
            50,
            false,
            3),
    BACKED_FISH("1 sardine + 1 salmon + 1 wheat = 1 backed fish",
            new HashMap<>(),
            75,
            false,
            100),
    SALAD("1 leek + 1 dandelion = 1 salad",
            new HashMap<>(),
            113,
            false,
            110),
    OLMELET("1 egg + 1 milk = 1 olmelet",
            new HashMap<>(),
            100,
            false,
            125),
    PUMPKIN_PIE("1 pumpkin + 1 wheat flour + 1 milk + 1 sugar = 1 pumpkin pie",
            new HashMap<>(),
            225,
            false,
            385),
    SPAGHETTI("1 wheat flour + 1 tomato = 1 spaghetti",
            new HashMap<>(),
            75,
            false,
            120),
    PIZZA("1 wheat flour + 1 tomato + 1 cheese = 1 pizza",
            new HashMap<>(),
            150,
            false,
            300),
    TORTILLA("1 corn = 1 tortilla",
            new HashMap<>(),
            50,
            false,
            50),
    MAKI_ROLL("1 any fish + 1 rice + 1 fiber = 1 maki roll",
            new HashMap<>(),
            100,
            false,
            220),
    TRIPLE_SHOT_ESPRESSO("3 coffee = 1 triple shot espresso",
            new HashMap<>(),
            200,
            true,
            450),
    COOKIE("1 wheat flour + 1 sugar + 1 egg = 1 cookie",
            new HashMap<>(),
            90,
            false,
            140),
    HASH_BROWNS("1 potato + 1 oil = 1 hash browns",
            new HashMap<>(),
            90,
            true,
            120),
    PANCAKES("1 wheat flour + 1 egg = 1 pancakes",
            new HashMap<>(),
            90,
            true,
            80),
    FRUIT_SALAD("1 blueberry + 1 melon + 1 apricot = 1 fruit salad",
            new HashMap<>(),
            263,
            false,
            450),
    RED_PLATE("1 red cabbage + 1 radish = 1 red plate",
            new HashMap<>(),
            240,
            true,
            400),
    BREAD("1 wheat flour = 1 bread",
            new HashMap<>(),
            50,
            false,
            60),
    SALMON_DINNER("1 salmon + 1 amaranth + 1 kale = 1 salmon dinner",
            new HashMap<>(),
            125,
            false,
            300),
    VEGETABLE_MEDLEY("1 tomato + 1 beet = 1 vegetable medley",
            new HashMap<>(),
            165,
            false,
            120),
    FARMERS_LAUNCH("1 omelet + 1 parsnip = 1 farmer launch",
            new HashMap<>(),
            200,
            true,
            150),
    SURVIVAL_BURGERS("1 bread + 1 carrot + 1 eggplant = 1 survival burger",
            new HashMap<>(),
            125,
            true,
            180),
    DISH_O_THE_SEA("2 sardines + 1 hash browns = 1 dish O' the sea",
            new HashMap<>(),
            150,
            true,
            220),
    SEA_FORM_PUDDING("1 flounder + 1 midnight carp = 1 sea form pudding",
            new HashMap<>(),
            175,
            true,
            300),
    MINERS_TREAT("2 carrot + 1 suger + 1 milk = 1 miner treat",
            new HashMap<>(),
            125,
            true,
            200);

    public  final String recipe;
    public final HashMap<BackPackable, Integer> ingredients;
    public final int energy;
    public final boolean buff;
    public final int price;

    FoodType(String recipe, HashMap<BackPackable, Integer> ingredients, int energy, boolean buff, int price) {
        this.recipe = recipe;
        this.ingredients = ingredients;
        this.energy = energy;
        this.buff = buff;
        this.price = price;
    }
}
